helmCharts:
  - name: clickhouse
    repo: https://helm.altinity.com
    releaseName: clickhouse
    namespace: clickhouse
    version: 0.3.7
    valuesFile: values.yaml

resources:
  - clickhouse-installation.yaml
