helmCharts:
  - name: clickhouse
    repo: https://helm.altinity.com
    releaseName: clickhouse
    namespace: clickhouse
    valuesFile: values.yaml
    skipCRDs: true


resources:
  - clickhouse-installation.yaml
